export {default as Navbar} from "./navbar.jsx"
export {default as MovieCard} from "./movieCard.jsx"
export {default as Hero} from "./hero.jsx"
export {default as ThemeToggle} from "./themeToggle.jsx"
export {default as LanguageSwitcher} from "./languageSwitcher.jsx"